services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    # Ensure dependencies are installed before starting
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo
    # For development with live reload, uncomment below and use 'npm run start:dev' in command
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    #   - /usr/src/app/dist
    # environment:
    #   - MONGODB_URI=mongodb://mongo:27017/products
    #   - NODE_ENV=development
    # command: sh -c "npm install && npm run start:dev"

volumes:
  mongo_data: