services:
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm install && npm run start:dev"
    ports:
      - 3000:3000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo

volumes:
  mongo_data: